ComputerTeam.create(team_name: "Pirates", team_city: "Pittsburgh", gameday_id: "pitmlb")
ComputerTeam.create(team_name: "Tigers", team_city: "Detroit", gameday_id: "detmlb")
ComputerTeam.create(team_name: "Phillies", team_city: "Philadelphia", gameday_id: "phimlb")
ComputerTeam.create(team_name: "Padres", team_city: "San Diego", gameday_id: "sdnmlb")
ComputerTeam.create(team_name: "White Sox", team_city: "Chicago", gameday_id: "chamlb")
ComputerTeam.create(team_name: "Twins", team_city: "Minnesota", gameday_id: "minmlb")
ComputerTeam.create(team_name: "Rays", team_city: "Tampa Bay", gameday_id: "tbamlb")
ComputerTeam.create(team_name: "Indians", team_city: "Cleveland", gameday_id: "clemlb")
ComputerTeam.create(team_name: "Cardinals", team_city: "St. Louis", gameday_id: "slnmlb")
ComputerTeam.create(team_name: "Rockies", team_city: "Colorado", gameday_id: "colmlb")
ComputerTeam.create(team_name: "Nationals", team_city: "Washington", gameday_id: "wasmlb")
ComputerTeam.create(team_name: "Blue Jays", team_city: "Toronto", gameday_id: "tormlb")
ComputerTeam.create(team_name: "Rangers", team_city: "Texas", gameday_id: "texmlb")
ComputerTeam.create(team_name: "Cubs", team_city: "Chicago", gameday_id: "chnmlb")
ComputerTeam.create(team_name: "Astros", team_city: "Houston", gameday_id: "houmlb")
ComputerTeam.create(team_name: "Dodgers", team_city: "Los Angeles", gameday_id: "lanmlb")
ComputerTeam.create(team_name: "Brewers", team_city: "Milwaukee", gameday_id: "milmlb")
ComputerTeam.create(team_name: "Giants", team_city: "San Francisco", gameday_id: "sfnmlb")
ComputerTeam.create(team_name: "Braves", team_city: "Atlanta", gameday_id: "atlmlb")
ComputerTeam.create(team_name: "Yankees", team_city: "New York", gameday_id: "nyamlb")
ComputerTeam.create(team_name: "Orioles", team_city: "Baltimore", gameday_id: "balmlb")
ComputerTeam.create(team_name: "Reds", team_city: "Cincinnati", gameday_id: "cinmlb")
ComputerTeam.create(team_name: "Royals", team_city: "Kansas City", gameday_id: "kcamlb")
ComputerTeam.create(team_name: "Diamondbacks", team_city: "Arizona", gameday_id: "arimlb")
ComputerTeam.create(team_name: "Mariners", team_city: "Seattle", gameday_id: "seamlb")
ComputerTeam.create(team_name: "Marlins", team_city: "Miami", gameday_id: "miamlb")
ComputerTeam.create(team_name: "Mets", team_city: "New York", gameday_id: "nynmlb")
ComputerTeam.create(team_name: "Red Sox", team_city: "Boston", gameday_id: "bosmlb")
ComputerTeam.create(team_name: "Angels", team_city: "Los Angeles", gameday_id: "anamlb")
ComputerTeam.create(team_name: "Athletics", team_city: "Oakland", gameday_id: "oakmlb")
